puts "The students of Villains Academy"
puts "---------------"
puts "Dr Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "The Terminator"
puts "Fredy Kreuger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"